In [23]:
from tensorflow import keras
import tensorflow as tf
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

In [24]:
dataset = pd.read_csv('dataset.csv')
dataset.columns


Index(['itemid', 'shopid', 'name', 'url', 'image', 'created', 'price'], dtype='object')

In [25]:
min_max_sc = MinMaxScaler()
dataset[['price']] = min_max_sc.fit_transform(dataset[['price']])
dataset.head()

itemid     shopid                                               name  \
0   3787635903  252709596  Streetwear Celana Olahraga Pria Katun Kasual C...   
1  11359837015    6474527  SETCEL HITAM SET CELANA JUMBO SET BAHAN RAJUT ...   
2  15409657235  303783498  FREE ONGKIR/ JENIE / SOOYUN/ BOLERO LALISA/ CA...   
3  15908100313    5591523                  Kalula Outer Scarf by This.For.Uu   
4  11445308177  252709596         Jaket Wanita Olin Button Gaya Casual Korea   

                                                 url  \
0  https://shopee.co.id/Streetwear-Celana-Olahrag...   
1  https://shopee.co.id/SETCEL-HITAM-SET-CELANA-J...   
2  https://shopee.co.id/FREE-ONGKIR-JENIE-SOOYUN-...   
3  https://shopee.co.id/Kalula-Outer-Scarf-by-Thi...   
4  https://shopee.co.id/Jaket-Wanita-Olin-Button-...   

                                               image              created  \
0  {bc03c334465ef3cfb946fdb1062b6cc3,35ba8d147561...  2021-04-28 10:26:16   
1  {af656ef3769da0d1e319d3978a074020,c2af8fbcd3d9...  2021-10-15 07:56:46   
2  {afcc598e995399f25bef797092ce1633,164e70056421...  2021-11-30 13:46:39   
3                 {07d4c6fe64bd13eb5f6976f03a24be98}  2021-11-28 03:29:20   
4  {b70335366a215eb39f2837f4aa7d17e4,bcda6e5bb308...  2021-09-04 14:25:33   

      price  
0  0.000082  
1  0.000273  
2  0.000082  
3  0.000116  
4  0.000079

In [26]:
train, test = train_test_split(dataset, test_size=0.2)
train.head()

itemid     shopid  \
28389  9611408802  241411089   
20193  2378440130  109826396   
40454  5545117465   73424710   
86555  7760669195  219569755   
94255  7048402116  282191467   

                                                    name  \
28389  {{ORIGINAL}} Pelindung Kepala Head Protector H...   
20193  Sen Tempel Lampu Sein Tempel Segitiga LED Univ...   
40454           Wheeldop Tutup Velg Peleg Sepeda (Motor)   
86555  [✅COD] Celana Dalam Wanita Premium Quality CD ...   
94255  Jaket Pria Wanita Cougle Float Noise Parasut T...   

                                                     url  \
28389  https://shopee.co.id/-ORIGINAL-Pelindung-Kepal...   
20193  https://shopee.co.id/Sen-Tempel-Segitiga-LED-U...   
40454  https://shopee.co.id/Wheeldop-Tutup-Velg-Peleg...   
86555  https://shopee.co.id/-%E2%9C%85COD-Celana-Dala...   
94255  https://shopee.co.id/x-x-x-i.7048402116.282191467   

                                                   image              created  \
28389  {cffa65f7ed95b9df7528b18d69389b84,cca4f963754b...  2021-01-23 16:40:21   
20193  {764ff06db953af367ef60f488dafb5eb,95e7eacd1902...  2019-07-02 03:03:12   
40454  {e5020dddb004210a246154e7c39b3c02,ed5c56101979...  2020-08-05 07:41:42   
86555  {b73ea27a9b07515ee434b8d5a2f69312,7ad6840babf1...  2020-11-02 17:48:21   
94255  {ea49b69d53a37e19ea7bc99402d0eaaa,130e2aea6be4...  2020-08-23 11:19:31   

          price  
28389  0.000309  
20193  0.000021  
40454  0.000182  
86555  0.000036  
94255  0.000233

# create model

# Test loss function

In [62]:
y_true = [12, 20, 29., 60.]
y_pred = [14., 18., 27., 55.]
mse = tf.keras.losses.MeanSquaredError()
mse(y_true, y_pred).numpy()


9.25

# 1 D Layer

seperti flattening

In [49]:
input_shape = (1,4,10)
x = tf.random.normal(input_shape)
print(x)
y = tf.keras.layers.GlobalAveragePooling1D()(x)
print(y.shape)

tf.Tensor(
[[[ 1.5052961   0.302629   -0.33753902 -1.7845367   0.22136006
   -1.1632321   1.1316687   0.58353525  0.6356116   1.4086324 ]
  [ 0.7464467  -0.8878024   0.05895403  1.5185667  -0.20384908
    1.4984776  -0.1936614   1.331584    0.08394321  1.5280132 ]
  [ 0.07215419 -0.14074957  1.3221294  -1.1650016   1.0759389
   -0.7487836   1.1834902  -1.8795924  -1.673398   -0.9549372 ]
  [ 0.4954189  -0.00541644 -0.50666505 -1.6927085  -0.737521
   -0.7999481   0.72518855 -1.206751    0.07502055 -0.5932916 ]]], shape=(1, 4, 10), dtype=float32)
(1, 10)


# Embeded Layer

In [51]:
embedding_layer = keras.layers.Embedding(1000, 16)

In [53]:
result = embedding_layer(tf.constant([1, 2, 3]))
result.numpy().shape

(3, 16)

# vectorize layer

In [57]:
vocab_size = 100000
sequence_length = 100

# Use the text vectorization layer to normalize, split, and map strings to
# integers. Note that the layer uses the custom standardization defined above.
# Set maximum_sequence length as all samples are not of the same length.
vectorize_layer = keras.layers.TextVectorization(
    standardize= "lower_and_strip_punctuation",
    max_tokens=vocab_size,
    output_mode='int',
    output_sequence_length=sequence_length)

vectorize_layer.adapt(train.name)

vectorize_layer("MOHLER Coloring Rose Pink (BELI 1 GRATIS 1)")

<tf.Tensor: shape=(100,), dtype=int64, numpy=
array([13248,  5602,   698,   311,  1122,    13,   394,    13,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0,     0,     0,     0,     0,     0,     0,     0,     0,
           0], dtype=int64)>

In [30]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Embedding, GlobalAveragePooling1D

In [76]:
embedding_dim=50

model = Sequential([
  tf.keras.Input(shape=(1,), dtype=tf.string),
  vectorize_layer,
  Embedding(vocab_size, embedding_dim, name="embedding"),
  GlobalAveragePooling1D(),
  Dense(50, activation='relu'),
  Dense(20, activation='relu'),
  Dense(1)
])

model.compile(optimizer='adam',
  loss=['mean_squared_error'],
  metrics=['accuracy'])

In [78]:
model.fit(train.name, train.price, batch_size=300)

255/255 [==============================] - 8s 30ms/step - loss: 1.3556e-05 - accuracy: 0.0030


In [72]:
pred = model.predict(["gamis maxmara Lux LD 100cm 140cm Ukuran L XL XXL XXXL XXXXL"])
min_max_sc.inverse_transform(pred)

1/1 [==============================] - 0s 33ms/step


array([[236489.92]], dtype=float32)